name: shirne_dialog
description: A alert package to use alert and toast within one line code.
version: 1.0.1
author: shirne <shirne@126.com>
homepage: https://github.com/shirne/shirne_dialog

environment:
  sdk: ">=2.0.0-dev.40.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
