name: shirne_dialog
description: A flutter package to use alert, toast, popup, snack, imagePreview, loading etc. with customizable style in anywhere.
version: 4.5.1
homepage: https://shirne.github.io/dialog/
repository: https://github.com/shirne/shirne_dialog
imagePreview: https://github.com/shirne/shirne_dialog/blob/master/preview/dialog.gif

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  combined_animation: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: dicons
      fonts:
        - asset: assets/fonts/icons.ttf