name: shirne_dialog
description: A alert package to use alert and toast within one line code.
version: 1.2.1
homepage: https://www.shirne.com/demo/easydialog/
repository: https://github.com/shirne/shirne_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
