name: shirne_dialog
description: A package to use alert, confirm, toast, snack and popup within one line code.
version: 1.2.2
homepage: https://www.shirne.com/demo/easydialog/
repository: https://github.com/shirne/shirne_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
